name: Daily Harvest Sync
on:
  schedule:
    - cron: "0 22 * * *" # Execute once a day, afterwork 
env:
  PYTHON_VERSION: 3.9

jobs:
  update-hours:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Set up python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Populate environment variables into vars and execute python script
      env:
        TOKEN: ${{ secrets.TOKEN }}
        ACCOUNT_ID: ${{secrets.ACCOUNT_ID}}
        PAYROLL_PROJECT_ID: ${{secrets.PAYROLL_PROJECT_ID}}
        SOFTWARE_DEVELOPMENT_TASK_ID: ${{secrets.SOFTWARE_DEVELOPMENT_TASK_ID}}
        AMOUNT_HOURS: ${{vars.AMOUNT_HOURS}}
      run: |
        python -m pip install -r requirements.txt --upgrade pip
        python harvest_automation/harvest-automation.py
